# Use the official Node.js image as a base image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps --network-timeout=100000

# Install TypeScript and nodemon globally
RUN npm install -g typescript nodemon

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Health check to indicate when the service is ready
HEALTHCHECK --interval=10s --timeout=10s --start-period=30s --retries=20 \
  CMD curl -f http://localhost:3000/api/health || exit 1

# Start the Node.js application
CMD ["sh", "-c", "npm run build && nodemon --watch src --ext ts --exec 'npm run build && node dist/index.js'"]