import React, { useState, useEffect } from 'react';
import {
    TextField,
    FormControl,
    InputLabel,
    Select,
    MenuItem,
    Dialog,
    SelectChangeEvent
} from '@mui/material';
import { MessageComponentProps, MessageType, getDefaultMessageForm } from '../../../../types/MessageTypes';
import EnhancedSelect from '../../common/enhanced_select/EnhancedSelect';
import EnhancedFile from '../../file/file/EnhancedFile';
import EnhancedTaskResponse from '../../task_response/task_response/EnhancedTaskResponse';
import { useApi } from '../../../../contexts/ApiContext';
import GenericFlexibleView from '../../common/enhanced_component/FlexibleView';
import { FileReference } from '../../../../types/FileTypes';
import { TaskResponse } from '../../../../types/TaskResponseTypes';

const MessageFlexibleView: React.FC<MessageComponentProps> = ({
    item,
    onChange,
    mode,
    handleSave,
    chatId
}) => {
    const { fetchItem } = useApi();
    const [form, setForm] = useState<Partial<MessageType>>(getDefaultMessageForm());
    const [activeAccordion, setActiveAccordion] = useState<string | null>(null);
    const [dialogOpen, setDialogOpen] = useState(false);
    const [dialogContent, setDialogContent] = useState<React.ReactNode | null>(null);

    useEffect(() => {
        if (item) {
            setForm({ ...getDefaultMessageForm(), ...item });
        }
    }, [item]);

    const isEditMode = mode === 'edit' || mode === 'create';

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        onChange({ ...form, [name]: value });
    };

    const handleSelectChange = (e: SelectChangeEvent<string>) => {
        const { name, value } = e.target;
        onChange({ ...form, [name as string]: value });
    };

    const handleFileReferencesChange = async (selectedIds: string[]) => {
        const references = await Promise.all(selectedIds.map(id => fetchItem('files', id))) as FileReference[];
        onChange({ ...form, references });
    };

    const handleTaskResponsesChange = async (selectedIds: string[]) => {
        const taskResponses = await Promise.all(selectedIds.map(id => fetchItem('taskresults', id))) as TaskResponse[];
        onChange({ ...form, task_responses: taskResponses });
    };

    const handleAccordionToggle = (accordion: string | null) => {
        setActiveAccordion(prevAccordion => prevAccordion === accordion ? null : accordion);
    };

    const handleViewDetails = (type: 'file' | 'taskResponse', itemId: string) => {
        let content;
        switch (type) {
            case 'file':
                content = <EnhancedFile mode="card" itemId={itemId} fetchAll={false} />;
                break;
            case 'taskResponse':
                content = <EnhancedTaskResponse mode="card" itemId={itemId} fetchAll={false} />;
                break;
        }
        setDialogContent(content);
        setDialogOpen(true);
    };

    const title = mode === 'create' ? 'Create New Message' : mode === 'edit' ? 'Edit Message' : 'Message Details';
    const saveButtonText = form._id ? 'Update Message' : 'Create Message';

    return (
        <GenericFlexibleView
            elementType='Message'
            title={title}
            onSave={handleSave}
            saveButtonText={saveButtonText}
            isEditMode={isEditMode}
        >
            <FormControl fullWidth margin="normal">
                <InputLabel>Role</InputLabel>
                <Select
                    name="role"
                    value={form.role || ''}
                    onChange={handleSelectChange}
                    disabled={!isEditMode}
                >
                    <MenuItem value="user">User</MenuItem>
                    <MenuItem value="assistant">Assistant</MenuItem>
                    <MenuItem value="system">System</MenuItem>
                    <MenuItem value="tool">Tool</MenuItem>
                </Select>
            </FormControl>

            <TextField
                fullWidth
                multiline
                rows={4}
                name="content"
                label="Content"
                value={form.content || ''}
                onChange={handleInputChange}
                margin="normal"
                disabled={!isEditMode}
            />

            <FormControl fullWidth margin="normal">
                <InputLabel>Generated By</InputLabel>
                <Select
                    name="generated_by"
                    value={form.generated_by || ''}
                    onChange={handleSelectChange}
                    disabled={!isEditMode}
                >
                    <MenuItem value="user">User</MenuItem>
                    <MenuItem value="llm">LLM</MenuItem>
                    <MenuItem value="tool">Tool</MenuItem>
                </Select>
            </FormControl>

            <EnhancedSelect<FileReference>
                componentType="files"
                EnhancedComponent={EnhancedFile}
                selectedItems={form.references || []}
                onSelect={handleFileReferencesChange}
                isInteractable={isEditMode}
                multiple
                label="File References"
                activeAccordion={activeAccordion}
                onAccordionToggle={handleAccordionToggle}
                onView={(id) => handleViewDetails("file", id)}
                accordionEntityName="file-references"
            />

            <EnhancedSelect<TaskResponse>
                componentType="taskresults"
                EnhancedComponent={EnhancedTaskResponse}
                selectedItems={form.task_responses || []}
                onSelect={handleTaskResponsesChange}
                isInteractable={isEditMode}
                multiple
                label="Task Responses"
                activeAccordion={activeAccordion}
                onAccordionToggle={handleAccordionToggle}
                onView={(id) => handleViewDetails("taskResponse", id)}
                accordionEntityName="task-responses"
            />

            <Dialog open={dialogOpen} onClose={() => setDialogOpen(false)}>
                {dialogContent}
            </Dialog>
        </GenericFlexibleView>
    );
};

export default MessageFlexibleView;