import React from 'react';
import {
    Typography,
} from '@mui/material';
import { Person, AccessTime, AttachFile, TextSnippet, Engineering, PersonPin } from '@mui/icons-material';
import { MessageComponentProps } from '../../../../types/MessageTypes';
import CommonCardView from '../../common/enhanced_component/CardView';
import { hasAnyReferences } from '../../../../types/ReferenceTypes';
import { CodeBlock } from '../../../ui/markdown/CodeBlock';
import AliceMarkdown, { CustomBlockType } from '../../../ui/markdown/alice_markdown/AliceMarkdown';
import DataClusterManager from '../../data_cluster/data_cluster_manager/DataClusterManager';

const MessageCardView: React.FC<MessageComponentProps> = ({
    item,
}) => {
    if (!item) {
        return <Typography>No message data available.</Typography>;
    }

    const listItems = [
        {
            icon: <TextSnippet />,
            primary_text: "Content",
            secondary_text:
                <AliceMarkdown
                    enabledBlocks={[CustomBlockType.ALICE_DOCUMENT, CustomBlockType.ANALYSIS]}
                    role={item.role}
                >
                    {item.content}
                </AliceMarkdown>
        },
        {
            icon: <Person />,
            primary_text: "Role",
            secondary_text: item.role
        },
        {
            icon: <PersonPin />,
            primary_text: "Assistant",
            secondary_text: item.assistant_name ?? "N/A"
        },
        {
            icon: <Engineering />,
            primary_text: "Generated By",
            secondary_text: item.generated_by
        },
        {
            icon: <AttachFile />,
            primary_text: "References",
            secondary_text: item.references && hasAnyReferences(item.references) ? <DataClusterManager dataCluster={item.references} /> : <Typography>"N/A"</Typography>,
        },
        {
            icon: <Person />,
            primary_text: "Metadata",
            secondary_text: item.creation_metadata ? <CodeBlock language="json" code={JSON.stringify(item.creation_metadata, null, 2)} /> : "N/A",
        },
        {
            icon: <AccessTime />,
            primary_text: "Created At",
            secondary_text: new Date(item.createdAt || '').toLocaleString()
        },
    ];

    return (
        <CommonCardView
            elementType='Message'
            title={item.role}
            subtitle={`Type: ${item.type}`}
            id={item._id}
            listItems={listItems}
            item={item}
            itemType='messages'
        />
    );
};

export default MessageCardView;